apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  namespace: webapp
spec:
  capacity:
    storage: 5Gi
  storageClassName: standard
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/proxy/db/password.txt"
